---
- name: "Configuring config.json for:"
  ansible.builtin.debug:
    var: item

- name: Get user data
  ansible.builtin.user:
    name: "{{ item }}"
  register: user_data

- name: Creates docker config directory
  ansible.builtin.file:
    path: "{{ user_data.home }}/.docker/"
    state: directory
    owner: "{{ user_data.name }}"
    group: "{{ user_data.name }}"
    mode: '0655'

- name: Check if docker config exists
  ansible.builtin.stat:
    path: '{{ user_data.home }}/.docker/config.json'
  register: stat_result

- name: Read docker config file
  ansible.builtin.slurp:
    src: '{{ user_data.home }}/.docker/config.json'
  register: config_file
  when: stat_result.stat.exists

- name: Set fact original_content
  ansible.builtin.set_fact:
    original_content: "{{ config_file.content | b64decode | from_json if config_file.content is defined else {} }}"

- name: Add cred_helper_config to docker config json object
  ansible.builtin.set_fact:
    result_var: "{{ original_content | combine(cred_helper_config | to_json | from_json) }}"

- name: Write merged content to config file
  ansible.builtin.copy:
    content: "{{ result_var | to_nice_json }}"
    dest: '{{ user_data.home }}/.docker/config.json'
    owner: "{{ user_data.name }}"
    group: "{{ user_data.name }}"
    mode: '0600'
