---
- name: "Configuring config.json for:"
  debug:
    var: item

- name: Get user data
  user:
    name: "{{ item }}"
  register: user_data

- name: Creates docker config directory
  file:
    path: "{{ user_data.home }}/.docker/"
    state: directory
    owner: "{{ user_data.name }}"
    group: "{{ user_data.name }}"
    mode: '755'

- name: Check if docker config exists
  stat:
    path: '{{ user_data.home }}/.docker/config.json'
  register: stat_result

- name: Read docker config file
  slurp:
    src: '{{ user_data.home }}/.docker/config.json'
  register: config_file
  when: stat_result.stat.exists

- name: Set fact original_content
  set_fact:
    original_content: "{{ config_file.content | b64decode | from_json if config_file.content is defined else {} }}"

- name: Add cred_helper_config to docker config json object
  set_fact:
    result_var: "{{ original_content | combine(cred_helper_config | to_json | from_json) }}"

- name: Write merged content to config file
  copy:
    content: "{{ result_var | to_nice_json }}"
    dest: '{{ user_data.home }}/.docker/config.json'
    owner: "{{ user_data.name }}"
    group: "{{ user_data.name }}"
    mode: '600'
