---
- name: Update apt cache.
  apt:
    update_cache: yes
  changed_when: false

- name: Install amazon-ecr-credential-helper from package
  package:
    name: "{{ aws_ecr_cred_helper_pkg }}"
    state: present
