---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Include default vars from role
      include_vars:
        dir: vars/
        extensions:
          - 'yaml'
          - 'yml'
  tasks:
    - include_role:
        name: thiagoalmeidasa.aws-ecr-credential-helper
