---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Include default vars from role
      include_vars:
        dir: vars/
        extensions:
          - 'yaml'
          - 'yml'
  tasks:
    - name: Include role
      include_role:
        name: thiagoalmeidasa.aws_ecr_credential_helper
