---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "30 2 * * 0"

defaults:
  run:
    working-directory: 'thiagoalmeidasa.aws_ecr_credential_helper'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'thiagoalmeidasa.aws_ecr_credential_helper'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: debian:9
          - distro: debian:9
            playbook: playbook_force_binary.yml
          - distro: debian:10
          - distro: debian:10
            playbook: playbook_force_binary.yml
          - distro: debian:11
          - distro: debian:11
            playbook: playbook_force_binary.yml
          - distro: ubuntu:16.04
          - distro: ubuntu:16.04
            playbook: playbook_force_binary.yml
          - distro: ubuntu:18.04
          - distro: ubuntu:18.04
            playbook: playbook_force_binary.yml
          - distro: ubuntu:20.04
          - distro: ubuntu:20.04
            playbook: playbook_force_binary.yml
          - distro: ubuntu:22.04
          - distro: ubuntu:22.04
            playbook: playbook_force_binary.yml

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'thiagoalmeidasa.aws_ecr_credential_helper'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies.
        run: |
          pip3 install pipenv
          pipenv install --dev

      - name: Run Molecule tests.
        run: pipenv run molecule test
        # continue-on-error: ${{ matrix.experimental }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
